// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKlc_JDiOmQtkKZh-GaGm61KiMv1-XjwQ',
    appId: '1:400063563536:web:78063b8bdd260950740795',
    messagingSenderId: '400063563536',
    projectId: 'project-d57f9',
    authDomain: 'project-d57f9.firebaseapp.com',
    storageBucket: 'project-d57f9.appspot.com',
    measurementId: 'G-FB54XYESY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKFIGaCVt1FutY8YuLwHAzB8QUqV5pLWU',
    appId: '1:400063563536:android:a4a65e7bdfae4b62740795',
    messagingSenderId: '400063563536',
    projectId: 'project-d57f9',
    storageBucket: 'project-d57f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJVSVQ5FYkhQy8DFCKmtLDpV3Mu2xmVjg',
    appId: '1:400063563536:ios:400c12325cd37121740795',
    messagingSenderId: '400063563536',
    projectId: 'project-d57f9',
    storageBucket: 'project-d57f9.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJVSVQ5FYkhQy8DFCKmtLDpV3Mu2xmVjg',
    appId: '1:400063563536:ios:400c12325cd37121740795',
    messagingSenderId: '400063563536',
    projectId: 'project-d57f9',
    storageBucket: 'project-d57f9.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKlc_JDiOmQtkKZh-GaGm61KiMv1-XjwQ',
    appId: '1:400063563536:web:6edd40ab6252a145740795',
    messagingSenderId: '400063563536',
    projectId: 'project-d57f9',
    authDomain: 'project-d57f9.firebaseapp.com',
    storageBucket: 'project-d57f9.appspot.com',
    measurementId: 'G-QSQR585XPH',
  );
}
